version: "3"

volumes:
  zk-leader-volume:
  zk-follower-alpha-volume:
  zk-follower-beta-volume:

services:
  zk-leader:
    image: p4km9y/zookeeper
    volumes:
      - zk-leader-volume:/opt/zookeeper/volume
#    deploy:
#      placement:
#        constraints:
#          - node.labels.javot.node.id == alpha
  zk-follower-alpha:
    image: p4km9y/zookeeper
    environment:
      - ZK_LEADER=zk-leader
      - ZK_SLEEP=10
    volumes:
      - zk-follower-alpha-volume:/opt/zookeeper/volume
#    deploy:
#      placement:
#        constraints:
#          - node.labels.javot.node.id == beta
  zk-follower-beta:
    image: p4km9y/zookeeper
    environment:
      - ZK_LEADER=zk-leader
      - ZK_SLEEP=30
    volumes:
      - zk-follower-beta-volume:/opt/zookeeper/volume
#    deploy:
#      placement:
#        constraints:
#          - node.labels.javot.node.id == gamma
